package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	"server/graph/model"
)

// UpdateAccount is the resolver for the updateAccount field.
func (r *mutationResolver) UpdateAccount(ctx context.Context, fullName string, avatarURL *string) (model.UpdateAccountPayload, error) {
	panic(fmt.Errorf("not implemented: UpdateAccount - updateAccount"))
}

// RequestPhoneNumberVerificationToken is the resolver for the requestPhoneNumberVerificationToken field.
func (r *mutationResolver) RequestPhoneNumberVerificationToken(ctx context.Context, phoneNumber string) (model.RequestPhoneNumberVerificationTokenPayload, error) {
	panic(fmt.Errorf("not implemented: RequestPhoneNumberVerificationToken - requestPhoneNumberVerificationToken"))
}

// UpdateAccountPhoneNumber is the resolver for the updateAccountPhoneNumber field.
func (r *mutationResolver) UpdateAccountPhoneNumber(ctx context.Context, phoneNumber string, phoneNumberVerificationToken string) (model.UpdateAccountPhoneNumberPayload, error) {
	panic(fmt.Errorf("not implemented: UpdateAccountPhoneNumber - updateAccountPhoneNumber"))
}

// RemoveAccountPhoneNumber is the resolver for the removeAccountPhoneNumber field.
func (r *mutationResolver) RemoveAccountPhoneNumber(ctx context.Context) (model.RemoveAccountPhoneNumberPayload, error) {
	panic(fmt.Errorf("not implemented: RemoveAccountPhoneNumber - removeAccountPhoneNumber"))
}

// UpdateAccountAnalyticsPreference is the resolver for the updateAccountAnalyticsPreference field.
func (r *mutationResolver) UpdateAccountAnalyticsPreference(ctx context.Context, analyticsPreference model.AnalyticsPreferenceInputType) (*model.Account, error) {
	panic(fmt.Errorf("not implemented: UpdateAccountAnalyticsPreference - updateAccountAnalyticsPreference"))
}

// RemoveAccountAvatar is the resolver for the removeAccountAvatar field.
func (r *mutationResolver) RemoveAccountAvatar(ctx context.Context) (*model.Account, error) {
	panic(fmt.Errorf("not implemented: RemoveAccountAvatar - removeAccountAvatar"))
}
