package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	"server/graph/model"
)

// RequestEmailVerificationToken is the resolver for the requestEmailVerificationToken field.
func (r *mutationResolver) RequestEmailVerificationToken(ctx context.Context, email string, captchaToken string) (model.RequestEmailVerificationTokenPayload, error) {
	panic(fmt.Errorf("not implemented: RequestEmailVerificationToken - requestEmailVerificationToken"))
}

// VerifyEmail is the resolver for the verifyEmail field.
func (r *mutationResolver) VerifyEmail(ctx context.Context, email string, emailVerificationToken string, captchaToken string) (model.VerifyEmailPayload, error) {
	panic(fmt.Errorf("not implemented: VerifyEmail - verifyEmail"))
}

// RegisterWithPassword is the resolver for the registerWithPassword field.
func (r *mutationResolver) RegisterWithPassword(ctx context.Context, email string, emailVerificationToken string, password string, fullName string, captchaToken string) (model.RegisterWithPasswordPayload, error) {
	panic(fmt.Errorf("not implemented: RegisterWithPassword - registerWithPassword"))
}

// GeneratePasskeyRegistrationOptions is the resolver for the generatePasskeyRegistrationOptions field.
func (r *mutationResolver) GeneratePasskeyRegistrationOptions(ctx context.Context, email string, fullName string, captchaToken string) (model.GeneratePasskeyRegistrationOptionsPayload, error) {
	panic(fmt.Errorf("not implemented: GeneratePasskeyRegistrationOptions - generatePasskeyRegistrationOptions"))
}

// RegisterWithPasskey is the resolver for the registerWithPasskey field.
func (r *mutationResolver) RegisterWithPasskey(ctx context.Context, email string, emailVerificationToken string, passkeyRegistrationResponse string, passkeyNickname string, fullName string, captchaToken string) (model.RegisterWithPasskeyPayload, error) {
	panic(fmt.Errorf("not implemented: RegisterWithPasskey - registerWithPasskey"))
}

// GenerateAuthenticationOptions is the resolver for the generateAuthenticationOptions field.
func (r *mutationResolver) GenerateAuthenticationOptions(ctx context.Context, captchaToken string) (model.GenerateAuthenticationOptionsPayload, error) {
	panic(fmt.Errorf("not implemented: GenerateAuthenticationOptions - generateAuthenticationOptions"))
}

// GenerateReauthenticationOptions is the resolver for the generateReauthenticationOptions field.
func (r *mutationResolver) GenerateReauthenticationOptions(ctx context.Context, captchaToken string) (model.GenerateAuthenticationOptionsPayload, error) {
	panic(fmt.Errorf("not implemented: GenerateReauthenticationOptions - generateReauthenticationOptions"))
}

// LoginWithPasskey is the resolver for the loginWithPasskey field.
func (r *mutationResolver) LoginWithPasskey(ctx context.Context, authenticationResponse string, captchaToken string) (model.LoginWithPasskeyPayload, error) {
	panic(fmt.Errorf("not implemented: LoginWithPasskey - loginWithPasskey"))
}

// LoginWithPassword is the resolver for the loginWithPassword field.
func (r *mutationResolver) LoginWithPassword(ctx context.Context, login string, password string, captchaToken string) (model.LoginWithPasswordPayload, error) {
	panic(fmt.Errorf("not implemented: LoginWithPassword - loginWithPassword"))
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (*model.LogoutPayload, error) {
	panic(fmt.Errorf("not implemented: Logout - logout"))
}

// RequestPasswordReset is the resolver for the requestPasswordReset field.
func (r *mutationResolver) RequestPasswordReset(ctx context.Context, email string, captchaToken string) (model.RequestPasswordResetPayload, error) {
	panic(fmt.Errorf("not implemented: RequestPasswordReset - requestPasswordReset"))
}

// Verify2faPasswordResetWithAuthenticator is the resolver for the verify2faPasswordResetWithAuthenticator field.
func (r *mutationResolver) Verify2faPasswordResetWithAuthenticator(ctx context.Context, email string, passwordResetToken string, twoFactorToken string, captchaToken string) (model.Verify2FAPasswordResetWithAuthenticatorPayload, error) {
	panic(fmt.Errorf("not implemented: Verify2faPasswordResetWithAuthenticator - verify2faPasswordResetWithAuthenticator"))
}

// Verify2faPasswordResetWithPasskey is the resolver for the verify2faPasswordResetWithPasskey field.
func (r *mutationResolver) Verify2faPasswordResetWithPasskey(ctx context.Context, email string, passwordResetToken string, authenticationResponse string, captchaToken string) (model.Verify2FAPasswordResetWithPasskeyPayload, error) {
	panic(fmt.Errorf("not implemented: Verify2faPasswordResetWithPasskey - verify2faPasswordResetWithPasskey"))
}

// ResetPassword is the resolver for the resetPassword field.
func (r *mutationResolver) ResetPassword(ctx context.Context, email string, passwordResetToken string, newPassword string) (model.ResetPasswordPayload, error) {
	panic(fmt.Errorf("not implemented: ResetPassword - resetPassword"))
}

// UpdatePassword is the resolver for the updatePassword field.
func (r *mutationResolver) UpdatePassword(ctx context.Context, newPassword string) (model.UpdatePasswordPayload, error) {
	panic(fmt.Errorf("not implemented: UpdatePassword - updatePassword"))
}

// DeletePassword is the resolver for the deletePassword field.
func (r *mutationResolver) DeletePassword(ctx context.Context) (model.DeletePasswordPayload, error) {
	panic(fmt.Errorf("not implemented: DeletePassword - deletePassword"))
}

// DeleteOtherSessions is the resolver for the deleteOtherSessions field.
func (r *mutationResolver) DeleteOtherSessions(ctx context.Context) (*model.DeleteOtherSessionsPayload, error) {
	panic(fmt.Errorf("not implemented: DeleteOtherSessions - deleteOtherSessions"))
}

// DeleteSession is the resolver for the deleteSession field.
func (r *mutationResolver) DeleteSession(ctx context.Context, sessionID string) (model.DeleteSessionPayload, error) {
	panic(fmt.Errorf("not implemented: DeleteSession - deleteSession"))
}

// DeleteWebAuthnCredential is the resolver for the deleteWebAuthnCredential field.
func (r *mutationResolver) DeleteWebAuthnCredential(ctx context.Context, webAuthnCredentialID string) (model.DeleteWebAuthnCredentialPayload, error) {
	panic(fmt.Errorf("not implemented: DeleteWebAuthnCredential - deleteWebAuthnCredential"))
}

// UpdateWebAuthnCredential is the resolver for the updateWebAuthnCredential field.
func (r *mutationResolver) UpdateWebAuthnCredential(ctx context.Context, webAuthnCredentialID string, nickname string) (model.UpdateWebAuthnCredentialPayload, error) {
	panic(fmt.Errorf("not implemented: UpdateWebAuthnCredential - updateWebAuthnCredential"))
}

// GenerateWebAuthnCredentialCreationOptions is the resolver for the generateWebAuthnCredentialCreationOptions field.
func (r *mutationResolver) GenerateWebAuthnCredentialCreationOptions(ctx context.Context) (model.GeneratePasskeyCreationOptionsPayload, error) {
	panic(fmt.Errorf("not implemented: GenerateWebAuthnCredentialCreationOptions - generateWebAuthnCredentialCreationOptions"))
}

// CreateWebAuthnCredential is the resolver for the createWebAuthnCredential field.
func (r *mutationResolver) CreateWebAuthnCredential(ctx context.Context, passkeyRegistrationResponse string, nickname string) (model.CreateWebAuthnCredentialPayload, error) {
	panic(fmt.Errorf("not implemented: CreateWebAuthnCredential - createWebAuthnCredential"))
}

// RequestSudoModeWithPasskey is the resolver for the requestSudoModeWithPasskey field.
func (r *mutationResolver) RequestSudoModeWithPasskey(ctx context.Context, authenticationResponse string, captchaToken string) (model.RequestSudoModeWithPasskeyPayload, error) {
	panic(fmt.Errorf("not implemented: RequestSudoModeWithPasskey - requestSudoModeWithPasskey"))
}

// RequestSudoModeWithPassword is the resolver for the requestSudoModeWithPassword field.
func (r *mutationResolver) RequestSudoModeWithPassword(ctx context.Context, password string, captchaToken string) (model.RequestSudoModeWithPasswordPayload, error) {
	panic(fmt.Errorf("not implemented: RequestSudoModeWithPassword - requestSudoModeWithPassword"))
}

// RequestSudoModeWithAuthenticator is the resolver for the requestSudoModeWithAuthenticator field.
func (r *mutationResolver) RequestSudoModeWithAuthenticator(ctx context.Context, twoFactorToken string, captchaToken string) (model.RequestSudoModeWithAuthenticatorPayload, error) {
	panic(fmt.Errorf("not implemented: RequestSudoModeWithAuthenticator - requestSudoModeWithAuthenticator"))
}

// EnableAccount2faWithAuthenticator is the resolver for the enableAccount2faWithAuthenticator field.
func (r *mutationResolver) EnableAccount2faWithAuthenticator(ctx context.Context, token string) (model.SetAccount2FAPayload, error) {
	panic(fmt.Errorf("not implemented: EnableAccount2faWithAuthenticator - enableAccount2faWithAuthenticator"))
}

// DisableAccount2faWithAuthenticator is the resolver for the disableAccount2faWithAuthenticator field.
func (r *mutationResolver) DisableAccount2faWithAuthenticator(ctx context.Context) (model.DisableAccount2FAWithAuthenticatorPayload, error) {
	panic(fmt.Errorf("not implemented: DisableAccount2faWithAuthenticator - disableAccount2faWithAuthenticator"))
}

// GenerateAuthenticator2faChallenge is the resolver for the generateAuthenticator2faChallenge field.
func (r *mutationResolver) GenerateAuthenticator2faChallenge(ctx context.Context) (model.GenerateAuthenticator2FAChallengePayload, error) {
	panic(fmt.Errorf("not implemented: GenerateAuthenticator2faChallenge - generateAuthenticator2faChallenge"))
}

// Verify2faWithAuthenticator is the resolver for the verify2faWithAuthenticator field.
func (r *mutationResolver) Verify2faWithAuthenticator(ctx context.Context, token string, captchaToken string) (model.Verify2FAWithAuthenticatorPayload, error) {
	panic(fmt.Errorf("not implemented: Verify2faWithAuthenticator - verify2faWithAuthenticator"))
}

// Verify2faWithRecoveryCode is the resolver for the verify2faWithRecoveryCode field.
func (r *mutationResolver) Verify2faWithRecoveryCode(ctx context.Context, token string, captchaToken string) (model.Verify2FAWithRecoveryCodePayload, error) {
	panic(fmt.Errorf("not implemented: Verify2faWithRecoveryCode - verify2faWithRecoveryCode"))
}

// Generate2faRecoveryCodes is the resolver for the generate2faRecoveryCodes field.
func (r *mutationResolver) Generate2faRecoveryCodes(ctx context.Context) (model.Generate2FARecoveryCodesPayload, error) {
	panic(fmt.Errorf("not implemented: Generate2faRecoveryCodes - generate2faRecoveryCodes"))
}

// VerifyGoogleToken is the resolver for the verifyGoogleToken field.
func (r *mutationResolver) VerifyGoogleToken(ctx context.Context, token string) (model.VerifyGoogleTokenPayload, error) {
	panic(fmt.Errorf("not implemented: VerifyGoogleToken - verifyGoogleToken"))
}

// Viewer is the resolver for the viewer field.
func (r *queryResolver) Viewer(ctx context.Context) (model.ViewerPayload, error) {
	panic(fmt.Errorf("not implemented: Viewer - viewer"))
}

// PasswordResetToken is the resolver for the passwordResetToken field.
func (r *queryResolver) PasswordResetToken(ctx context.Context, resetToken string, email string) (model.PasswordResetTokenPayload, error) {
	panic(fmt.Errorf("not implemented: PasswordResetToken - passwordResetToken"))
}
